---
services:
  mycolog:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - XDG_DATA_HOME=${HOME}/.local/share/mycolog
    volumes:
      - ${HOME}/.local/share/mycolog:${HOME}/.local/share/mycolog:rw
