---
services:
  mycolog:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8082:8080"
    environment:
      - XDG_DATA_HOME=${HOME}/.local/share/mycolog
    volumes:
      - /opt/mycolog:${HOME}/.local/share/mycolog:rw
    restart: always
